[package]
name = "recursion-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-lang-casm.workspace = true
stwo-prover.workspace = true
stwo_cairo_air.workspace = true
serde_json.workspace = true
stwo-cairo-adapter.workspace = true
